### ISSUE TITLE
This is not how Bitcoin mining works

### ISSUE THREAD

**Issue by mindminerDC** [moracamilo/Bitcoin#1]
An increase in the number of transactions does not require an increase in the amount of mining hashpower.

**Comment by pgrange** [comment]
This sentence in the README suggests a linear model between the number of transactions and the amount of energy needed to validate them:


> Proportions in the adoption of technologies were converted to transactions assuming a global number of cashless transactions of 314,210,898,142 [WorldBank. Global Payment Systems Survey 2016. (Accessed February 28, 2018)]. At each time step, CO2e emissions for the given number of transactions were estimated based on the emissions generated to mine that number of transactions in 2017.


However, according to [Bitcoin: A Peer-to-Peer Electronic Cash System](https://bitcoin.org/bitcoin.pdf) the energy needed seems  related to the number of nodes supporting the network (not using it but supporting it) and the number of blocks which is assumed to be 1 every 10 minutes.

@moracamilo could you elaborate on your model about energy consumption and explain how you correlate energy consumption and number of transactions ?

Regards,

**Comment by Kixunil** [comment]
Things that aren't accounted for:

* Halvings
* Earth population as a limit for transaction demand
* L2 scaling solutions
* Changes in electricity sources

**Comment by RichardRed0x** [comment]
> However, reducing Bitcoin’s carbon footprint should not rest solely on some yet-to-be-developed hardware but include simple modifications to the overall system, such as adding more transactions per block or reducing the difficulty or time required to resolve the proof-of-work — both of which could result in immediate electricity reductions for Bitcoin usage.

The point at which all credibility vanished. I'm surprised to see a statement like this in a journal like Nature Climate.

**Comment by Camilo-Mora** [comment]
We agree that there are several unknowns to precisely calculate the full CO2 emissions of Bitcoin. Part of the novelty of this paper was to provide approximations to those numbers. Further we established statistical approaches to Estimate likely margins of variability. Interestingly, at least two other papers, I am aware of, have used different approaches to estimate CO emmisions from Bitcoin, with relatively similar results.
Please also be aware, that the second part of the paper was an scenario, in which we simply ask the question "what if" Bitcoin goes viral, everything else remaining the same. These types of exercises are done in risk assessments, not to predict the future, but assess likely consequences. We did not intend our paper as a criticism of Bitcoin, rather, we wanted to point out the need for increasing efficiency in its approach if its environmental impacts are to be avoided, should it scale up.

**Comment by Kixunil** [comment]
I think I understand your idea. I believe there's a significant mistake in such reasoning:

> Bitcoin goes viral, everything else remaining the same.

What if 1 == 2?

Maybe fun, but practically useless question because it will never happen.

Bitcoin going viral and everything else staying the same is literally impossible because of the limited block size. Therefore L2 solutions MUST be used and accounted for. Otherwise, this analysis is completely useless. As mentioned above they also optimize energy efficiency.

I wonder do those other two papers take into account the feedback provided by technical community? If yes, I'd love to look at them.

**Comment by Camilo-Mora** [comment]
The web is full of debates about the possibility of this scenario of cryptocurrencies going mainstream happening or not...including even debates about changes on Bitcoin itself as the number of Bitcoin left to mine gets closer to all 21million bitcoins available. At more than $30,000 for each Bitcoin now, it is hard to image that there will be no motivation to scale up the use of cryptocurencies. 

However, we agree with you that unless massive changes take place going viral will not happen, that is precisely one of the points of our paper. The electricity demands alone will be hard to meet, and the environmental impacts way to much to be accepted by any standard.

https://www.investopedia.com/news/could-cryptocurrencies-replace-cash-bitcoin-flippening/
https://www.tradersmagazine.com/departments/cryptocurrencies/cryptocurrencies-vs-fiat-money/

**Comment by Kixunil** [comment]
The electricity demands are not related to scaling. There's literally a piece of code that makes electricity demand lower if it can't be met (by decreasing the difficulty of the computation). Yes, I've read the actual code.
